more rebootstrap bits, test, testing workflow in circle, build and publish container image in github actions

diff --git a/Pollyfile b/Pollyfile
--- a/Pollyfile
+++ b/Pollyfile
@@ -33,110 +33,151 @@
   
   run %q{useradd --uid 1000 --home-dir /home/app --create-home --shell /bin/bash app --groups docker,abc-otf,efg-nnn}
 
+  run %q{mkdir -p /polly-safe/git}
+  run %q{chown -Rv app. /polly-safe}
+
   #TODO: workdir module
   command("WORKDIR") {
     "/home/app/polly"
-  }
-
-  command("COPY") {
-    "--chown=app . /home/app/polly"
   }
 
   #TODO: this is hacked
   run %q{ln -sfv /home/app/polly/bin/polly /usr/local/bin/polly}
 
   run %q{chown -R app /home/app}
-}
 
-@deploy = image {
-  stage "deploy", @bootstrap.stage
-  #TODO: user module
   command("USER") {
     "app"
   }
 
-  run %q{bundle config set --local path /home/app/vendor/bundle}
-  run %q{bundle config set --local jobs 4}
-  run %q{bundle config set --local retry 3}
-  run %q{bundle config set --local deploment true}
-  run %q{bundle config set --local without development}
-  run %q{bundle install}
-}
+  run %q{git config --global user.email "you@example.com"}
+  run %q{git config --global user.name "Your Name"}
 
-@test = image {
-  stage "test", @deploy.stage
+  ##TODO: user module
+  #command("USER") {
+  #  "app"
+  #}
 
-  #TODO: user module
-  command("USER") {
-    "app"
+  #run %q{bundle config set --local path /home/app/vendor/bundle}
+  #run %q{bundle config set --local jobs 4}
+  #run %q{bundle config set --local retry 3}
+  #run %q{bundle config set --local deploment true}
+  #run %q{bundle config set --local without development}
+  #run %q{bundle install}
+
+  #TODO: more 
+  command("COPY") {
+    "--chown=app Gemfile polly.gemspec VERSION /home/app/polly"
   }
 
-  #TODO: workdir module
-  command("WORKDIR") {
-    "/home/app/polly"
+  run %q{bundle install --path=vendor/bundle --jobs=4 --retry=3 --without=development}
+
+  command("COPY") {
+    "--chown=app . /home/app/polly"
   }
-
-  run %q{bundle config set --local path /home/app/vendor/bundle}
-  run %q{bundle config set --local jobs 4}
-  run %q{bundle config set --local retry 3}
-  run %q{bundle config set --local deploment true}
-  run %q{bundle config unset --local without}
-  run %q{bundle config set --local with development}
-  run %q{bundle install}
-
-  #run %q{bundle install --path=~/vendor/bundle --jobs=4 --retry=3 --deployment --with "development"}
-  #run %q{ssh-add -l}
-
-  run %q{kubectl config set-context polly-ci}
-  run %q{kubectl config use-context polly-ci}
 }
+
+#@deploy = image {
+#  stage "deploy", @bootstrap.stage
+#}
+
+#@test = image {
+#  stage "test", @deploy.stage
+#
+#  #TODO: user module
+#  command("USER") {
+#    "app"
+#  }
+#
+#  #TODO: workdir module
+#  command("WORKDIR") {
+#    "/home/app/polly"
+#  }
+#
+#  run %q{bundle config set --local path /home/app/vendor/bundle}
+#  run %q{bundle config set --local jobs 4}
+#  run %q{bundle config set --local retry 3}
+#  run %q{bundle config set --local deploment true}
+#  run %q{bundle config unset --local without}
+#  run %q{bundle config set --local with development}
+#  run %q{bundle install}
+#
+#  #run %q{bundle install --path=~/vendor/bundle --jobs=4 --retry=3 --deployment --with "development"}
+#  #run %q{ssh-add -l}
+#
+#  run %q{kubectl config set-context polly-ci}
+#  run %q{kubectl config use-context polly-ci}
+#}
+
+# ghcr.io/unhookd/polly:3.0-rc1
+# @bootstrap.from
+# polly:latest
+
+workflow_image = "ghcr.io/unhookd/polly:3.0-rc1"
 
 @plain_workflow = Plan.new
 @plain_workflow.add_circleci_job("bootstrap",
-[{"image"=> @bootstrap.from, "user"=> "root"}],
-[{"run"=> {"name"=>"bootstrap", "command"=>"
-id app || (#{@bootstrap.command_list.join("; ")})
-chown -R app /home/app
-su app -s /bin/test -- -w $SSH_AUTH_SOCK || (chmod g+w $SSH_AUTH_SOCK && chgrp 1000 $SSH_AUTH_SOCK && chgrp 1000 $(dirname $SSH_AUTH_SOCK) && chmod g+x $(dirname $SSH_AUTH_SOCK) && su app -s /bin/test -- -w $SSH_AUTH_SOCK)
-test -z $DOCKER_CERT_PATH || (chown -R 1000 $(dirname $DOCKER_CERT_PATH))
-su app -s /bin/bash -c '#{@deploy.command_list.join(" && ")}'
-su app -w SSH_AUTH_SOCK,DOCKER_CERT_PATH,DOCKER_HOST,DOCKER_MACHINE_NAME,DOCKER_TLS_VERIFY,NO_PROXY -s /bin/bash -c 'bundle exec polly build'
-docker run --rm=true polly:latest bundle exec rspec
-"}}], {}, "/home/app/polly")
+[{"image"=>workflow_image,"user"=>"root"}],
+[{"run"=>{"name"=>"bootstrap","command"=>"
+polly version
+"}}],{},"/home/app/polly")
+
+#id app || (#{@bootstrap.command_list.join("; ")})
+#chown -R app /home/app
+#su app -s /bin/test -- -w $SSH_AUTH_SOCK || (chmod g+w $SSH_AUTH_SOCK && chgrp 1000 $SSH_AUTH_SOCK && chgrp 1000 $(dirname $SSH_AUTH_SOCK) && chmod g+x $(dirname $SSH_AUTH_SOCK) && su app -s /bin/test -- -w $SSH_AUTH_SOCK)
+#test -z $DOCKER_CERT_PATH || (chown -R 1000 $(dirname $DOCKER_CERT_PATH))
+##su app -s /bin/bash -c '#{@deploy.command_list.join(" && ")}'
+##su app -w SSH_AUTH_SOCK,DOCKER_CERT_PATH,DOCKER_HOST,DOCKER_MACHINE_NAME,DOCKER_TLS_VERIFY,NO_PROXY -s /bin/bash -c 'bundle exec polly build'
+##docker run --rm=true polly:latest bundle exec rspec
 
 @plain_workflow.add_circleci_job("primary",
-[{"image"=>"polly:latest"}],
-[{"run"=>{"name"=>"rspec", "command" => "
-set -e
-set -x
-bundle exec rspec
-"}}], {"BUNDLE_PATH" => "/home/app/vendor/bundle"}, "/home/app/polly")
+[{"image"=>workflow_image}],
+[{"run"=>{"name"=>"rspec","command"=>"
+echo bundle install --path=vendor/bundle --with=development
+echo bundle exec rspec
+"}}],{},"/home/app/polly")
 @plain_workflow.depends("primary", "bootstrap")
 
-#TODO: workingdir module
-#@plain_workflow.add_circleci_job("bootstrap-5", [{"image"=>@bootstrap.from, "user"=> "root"}], [{"run"=>{"name"=>"sleep-5", "command"=>"sleep 5"}}], {}, "/")
-#@plain_workflow.add_circleci_job("bootstrap-30", [{"image"=>@bootstrap.from, "user"=> "root"}], [{"run"=>{"name"=>"sleep-30", "command"=>"sleep 30"}}], {}, "/")
-#@plain_workflow.add_circleci_job("bootstrap-60", [{"image"=>@bootstrap.from, "user"=> "root"}], [{"run"=>{"name"=>"sleep-60", "command"=>"sleep 60"}}], {}, "/")
-#@plain_workflow = Plan.new
-#@plain_workflow.add_circleci_job("bootstrap", [{"image"=>@bootstrap.from, "user"=> 0}], [{"run"=>{"name"=>"bootstrap", "command"=>"date && env && true"}}], {}, "/home/app/polly") #TODO: workingdir module
-#@plain_workflow.add_circleci_job("primary", [{"image"=>@bootstrap.from}], [{"run"=>{"name"=>"rspec", "command"=>"date && env && true"}}], {"BUNDLE_PATH" => "/home/app/vendor/bundle"}, "/home/app/polly")
-#@plain_workflow.depends("primary", "bootstrap")
+#"}}],{"BUNDLE_PATH"=>"/home/app/vendor/bundle"},"/home/app/polly")
 
-##gitch {
-##  "-y"
-##}
-##
-##gitch {<EOF
-###!/bin/sh
-##farts && foo
-##if [ false ];
-##then;
-##  echo;
-##fi
-##EOF
-##}
-##
-##
-##Polly.include(MyLocalModz.my_gitch)
 
-#TODO: git hook integration
+        # docker pull ghcr.io/unhookd/polly:3.0-rc1
+        # docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/unhookd/polly:3.0-rc1
+        # image: ubuntu:focal-20200606
+
+
+
+        #id app || (export  DEBIAN_FRONTEND=noninteractive; export  LC_ALL=C.UTF-8; export  LANG=en_US; export  LANGUAGE=en_US; export  ACCEPT_EULA=y; apt-get update; apt-get install -y locales locales-all; apt-get clean; rm -rf /var/lib/apt/lists/*; locale-gen --purge en_US; /bin/echo -e "LANG=$LANG\nLANGUAGE=$LANGUAGE\n" | tee /etc/default/locale; locale-gen $LANGUAGE; dpkg-reconfigure locales; apt-get update; apt-get install -y git curl apt-transport-https aptitude ca-certificates apt-utils software-properties-common docker.io build-essential libyaml-dev ruby2* libruby2* ruby-bundler rubygems-integration rake amazon-ecr-credential-helper; apt-get clean; rm -rf /var/lib/apt/lists/*; curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add; apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"; apt-get update; apt-get install -y kubectl; apt-get clean; rm -rf /var/lib/apt/lists/*; groupadd --gid 134 abc-otf; groupadd --gid 999 efg-nnn; useradd --uid 1001 --home-dir /home/app --create-home --shell /bin/bash app --groups docker,abc-otf,efg-nnn; ln -sfv /home/app/polly/bin/polly /usr/local/bin/polly; chown -R app /home/app)
+        #chown -R app .
+        #su app -s /bin/bash -c 'bundle config set --local path /home/app/vendor/bundle && bundle config set --local jobs 4 && bundle config set --local retry 3 && bundle config set --local deploment true && bundle config set --local without development && bundle install'
+        #su app -s /bin/bash -c 'bundle exec polly generate' > Dockerfile
+
+
+
+######TODO: workingdir module
+######@plain_workflow.add_circleci_job("bootstrap-5", [{"image"=>@bootstrap.from, "user"=> "root"}], [{"run"=>{"name"=>"sleep-5", "command"=>"sleep 5"}}], {}, "/")
+######@plain_workflow.add_circleci_job("bootstrap-30", [{"image"=>@bootstrap.from, "user"=> "root"}], [{"run"=>{"name"=>"sleep-30", "command"=>"sleep 30"}}], {}, "/")
+######@plain_workflow.add_circleci_job("bootstrap-60", [{"image"=>@bootstrap.from, "user"=> "root"}], [{"run"=>{"name"=>"sleep-60", "command"=>"sleep 60"}}], {}, "/")
+######@plain_workflow = Plan.new
+######@plain_workflow.add_circleci_job("bootstrap", [{"image"=>@bootstrap.from, "user"=> 0}], [{"run"=>{"name"=>"bootstrap", "command"=>"date && env && true"}}], {}, "/home/app/polly") #TODO: workingdir module
+######@plain_workflow.add_circleci_job("primary", [{"image"=>@bootstrap.from}], [{"run"=>{"name"=>"rspec", "command"=>"date && env && true"}}], {"BUNDLE_PATH" => "/home/app/vendor/bundle"}, "/home/app/polly")
+######@plain_workflow.depends("primary", "bootstrap")
+#####
+#######gitch {
+#######  "-y"
+#######}
+#######
+#######gitch {<EOF
+########!/bin/sh
+#######farts && foo
+#######if [ false ];
+#######then;
+#######  echo;
+#######fi
+#######EOF
+#######}
+#######
+#######
+#######Polly.include(MyLocalModz.my_gitch)
+#####
+######TODO: local ring0 git hook integration
